kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: kuberay-metrics
      honor_labels: true
      scrape_interval: 15s
      scheme: http
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: default
        - source_labels: [__meta_kubernetes_pod_label_ray_io_node_type]
          action: keep
          regex: head
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: metrics
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
