apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-results
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blob-fuse-mi
  mountOptions:
    - -o allow_other
    - --block-cache
    - --tmp-path=/mnt/blobcache
  csi:
    driver: blob.csi.azure.com
    # make sure volumeHandle is unique for every storage blob container in the cluster
    volumeHandle: "RESOURCE_GROUP_NAME#STORAGE_ACCOUNT_NAME#CONTAINER_NAME"
    volumeAttributes:
      resourceGroup: RESOURCE_GROUP_NAME
      storageAccount: STORAGE_ACCOUNT_NAME
      containerName: CONTAINER_NAME
      protocol: fuse
      AzureStorageAuthType: MSI
      AzureStorageIdentityClientID: MANAGED_IDENTITY_CLIENT_ID