---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-blob-results
  storageClassName:  blob-fuse-mi