---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse-mi
mountOptions:
- -o allow_other
- --use-attr-cache=true
- --cancel-list-on-mount-seconds=10
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --log-level=LOG_DEBUG
parameters:
  AzureStorageAuthType: MSI
  AzureStorageIdentityClientID: 8f229821-3235-49ca-8213-989f75b93d39
  protocol: fuse
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer