apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /tmp/ray/session_latest/logs/*
        Tag ray
        Path_Key true
        Refresh_Interval 5
    [FILTER]
        Name modify
        Match ray
        Add POD_LABELS ${POD_LABELS}
    [OUTPUT]
        Name azure
        Match *
        Log_Type_Key $kubernetes['labels']['${POD_LABELS}']
        Customer_ID ${ALA_WORKSPACE_ID}
        Shared_Key ${ALA_WORKSPACE_KEY}
